name: 🐛 Bug Report
description: 버그나 예상치 못한 동작을 신고해주세요
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["zzzz955"]

body:
  - type: markdown
    attributes:
      value: |
        버그 리포트를 작성해주셔서 감사합니다! 
        가능한 한 자세히 작성해주시면 빠른 해결에 도움이 됩니다.

  - type: dropdown
    id: component
    attributes:
      label: 🎯 컴포넌트
      description: 문제가 발생한 컴포넌트를 선택해주세요
      options:
        - Client (Qt GUI)
        - Server (C++ Backend)
        - Web (웹)
        - DB (데이터베이스)
        - Network (통신)
        - Game Logic (게임 로직)
        - Build System (빌드/배포)
        - Documentation (문서)
        - Other (기타)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 심각도
      description: 버그의 심각도를 선택해주세요
      options:
        - Critical (게임 실행 불가)
        - High (주요 기능 동작 안됨)
        - Medium (기능 일부 문제)
        - Low (사소한 UI 문제)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 문제 설명
      description: 발생한 문제를 자세히 설명해주세요
      placeholder: |
        예: 게임 보드에서 블록을 드래그할 때 애플리케이션이 크래시됩니다.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 재현 단계
      description: 문제를 재현하는 단계를 순서대로 작성해주세요
      placeholder: |
        1. 게임을 시작합니다
        2. 블루 플레이어로 첫 번째 블록을 선택합니다
        3. 보드의 모서리로 드래그합니다
        4. 애플리케이션이 크래시됩니다
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 예상 동작
      description: 어떤 동작을 예상했는지 설명해주세요
      placeholder: 블록이 정상적으로 배치되어야 합니다
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ 실제 동작
      description: 실제로 어떤 일이 발생했는지 설명해주세요
      placeholder: 애플리케이션이 종료되었습니다
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ 환경
      description: 테스트 환경을 선택해주세요
      options:
        - Windows 11 + Visual Studio 2022
        - Windows 10 + Visual Studio 2022
        - Linux + GCC
        - macOS + Clang
        - Other (아래 추가 정보에 명시)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 로그/오류 메시지
      description: 관련 로그나 오류 메시지가 있다면 첨부해주세요
      render: shell
      placeholder: |
        오류 메시지나 로그를 여기에 붙여넣어주세요

  - type: textarea
    id: additional
    attributes:
      label: 📎 추가 정보
      description: 스크린샷, 추가 컨텍스트 등 도움이 될 수 있는 정보
      placeholder: |
        - 스크린샷 첨부
        - 관련 설정 정보
        - 기타 참고사항

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 제출 전 확인해주세요
      options:
        - label: 최신 버전에서 테스트했습니다
          required: true
        - label: 중복 이슈가 없는지 확인했습니다
          required: true
        - label: 재현 단계를 검증했습니다
          required: true